import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link"


export async function getStaticProps() {
  const res = await fetch(`http://localhost:3000/api/test`);
  const data = await res.json()
  console.log(data)
  return {
    props: {message: data.message}, // will be passed to the page component as props
  }
}

export default function Home(prop) {
  return (
    <>
      <Head>
        <title>HOME</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Home page</h1>
      <ul>
        <Link href={"/About"}>About</Link>
      </ul>
      <h2>{prop.message }</h2>
    </>
  );
}

























// const [text, setText] = useState("loading")


//   useEffect(() => {
//     console.log("its work 1")
//     fetch(`http://localhost:3000/api/test`)
//     .then(res=>res.json())
//       .then(data => {
//         console.log("its work")
//       setText(data.message)
//     })
//   },[])